services:
  mongo:
    image: mongo:7
    container_name: checkhtml-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  api:
    build: .
    container_name: checkhtml-api
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      MONGO_URI: mongodb://mongo:27017
      DB_NAME: CheckHTML
    depends_on:
      - mongo

  worker:
    build: .
    container_name: checkhtml-worker
    environment:
      MONGO_URI: mongodb://mongo:27017
      DB_NAME: CheckHTML
    depends_on:
      - mongo
    # worker se ne vrti stalno; pokrene se i zavr≈°i (runOnce)
    command: ["node", "worker.js"]
    restart: "no"

volumes:
  mongo_data: